name: Deploy ke VPS

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout kode
      uses: actions/checkout@v3

    - name: Salin kode ke VPS
      uses: appleboy/scp-action@v0.1.4
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.DEPLOY_KEY }}
        source: "."
        target: "/home/${{ secrets.USERNAME }}/devops-hari6-cicd-basic"

    - name: Jalankan Docker Compose di VPS
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.DEPLOY_KEY }}
        script: |
          cd /home/${{ secrets.USERNAME }}/devops-hari6-cicd-basic
          docker compose down
          docker compose up -d --build
